name: Sabor del Himalaya CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Configurar e iniciar Docker Backend Pruebas
      run: |
        docker-compose build api_backend
    - name: Ejecutar Pruebas Automatizadas Pytest en Docker (Negocio/Domain)
      run: |
        docker-compose run --rm api_backend pytest tests/

  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Instalar NPM y Lint
      run: |
        cd frontend
        npm install
        npm run lint
